// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package boot

// Injectors from wire.go:

func InitializeApp() (App, error) {
	args := ParseAndBuildArg()
	app := NewApp(args)
	return app, nil
}
